[program:stripe-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/your-project/artisan queue:work --queue=stripe --tries=3 --timeout=300
autostart=true
autorestart=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/html/your-project/storage/logs/stripe-worker.log
stopwaitsecs=3600

[program:default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/your-project/artisan queue:work --queue=default --tries=3 --timeout=300
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/html/your-project/storage/logs/default-worker.log
stopwaitsecs=3600

[program:high-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/your-project/artisan queue:work --queue=high --tries=3 --timeout=300
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/your-project/storage/logs/high-worker.log
stopwaitsecs=3600

[program:monitoring-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/your-project/artisan queue:work --queue=monitoring --tries=3 --timeout=300
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/your-project/storage/logs/monitoring-worker.log
stopwaitsecs=3600